services:
  - type: web
    name: sipesand-backend
    env: node
    plan: free
    buildCommand: npm --prefix backend install && npm --prefix backend run prisma:generate && npm --prefix backend run prisma:push
    startCommand: node backend/src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: BASE_DOMAIN
        value: sipesand.web.id
