package id.web.sipesand.ananda.ui.theme
import androidx.compose.ui.graphics.Color
val RoyalBlueDark = Color(0xFF1A365D)
val SolidRoyalBlue = Color(0xFF1E3A8A)
val RoyalBluePrimary = Color(0xFF1E40AF)
val RoyalBlueMedium = Color(0xFF2563EB)
val RoyalBlueLight = Color(0xFF3B82F6)
val RoyalBlueSubtle = Color(0xFFEFF6FF)
val SoftGrayBg = Color(0xFFF8FAFC)
val SurfaceBackground = Color(0xFFF8FAFC)
val SurfaceCard = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF0F172A)
val TextSecondary = Color(0xFF64748B)
val TextMuted = Color(0xFF94A3B8)
val BorderColor = Color(0xFFE2E8F0)
val BorderSoft = Color(0xFFF1F5F9)
val StatusPaidGreen = Color(0xFF0F9D6A)
val StatusUnpaidRed = Color(0xFFE11D48)
val StatusPendingAmber = Color(0xFFD97706)
// pastel for icons
val PastelSky = Color(0xFFEFF6FF); val PastelSkyIcon = Color(0xFF0284C7)
val PastelIndigo = Color(0xFFEEF2FF); val PastelIndigoIcon = Color(0xFF4F46E5)
val PastelMint = Color(0xFFECFDF5); val PastelMintIcon = Color(0xFF10B981)
val PastelEmerald = Color(0xFFECFDF5); val PastelEmeraldIcon = Color(0xFF059669)
val PastelAmber = Color(0xFFFEF3C7); val PastelAmberIcon = Color(0xFFD97706)
val PastelOrange = Color(0xFFFFF7ED); val PastelOrangeIcon = Color(0xFFF97316)
val PastelRose = Color(0xFFFDF2F8); val PastelRoseIcon = Color(0xFFEC4899)
val PastelPurple = Color(0xFFF5F3FF); val PastelPurpleIcon = Color(0xFF7C3AED)
val PastelViolet = Color(0xFFFAF5FF); val PastelVioletIcon = Color(0xFF7C3AED)
val PastelTeal = Color(0xFFF0FDFA); val PastelTealIcon = Color(0xFF0D9488)
